name: ai_preview_studio
description: App Flutter multipropósito con Supabase + SQLite + IA (arquitectura limpia)
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- Core ---
  supabase_flutter: ^2.5.6
  flutter_riverpod: ^2.5.1

  # --- SQLite ---
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # --- UI y utilidades ---
  google_fonts: ^6.2.1
  image_picker: ^1.0.7
  uuid: ^4.3.3
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  flutter_spinkit: ^5.2.0
  provider: ^6.1.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.1

  # --- IA ---
  dart_openai: ^5.1.0
  google_generative_ai: ^0.4.7
  translator: ^1.0.4+1
  image: ^4.0.17
  http_parser: ^4.0.2
  cached_network_image: ^3.3.1

  # --- Realidad Virtual (360°) ---
  panorama: ^0.4.1
  sensors_plus: ^5.0.1
  shared_preferences: ^2.2.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env